# Generated by Django 5.2.10 on 2026-01-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=255)),
                ('letter_code', models.CharField(max_length=10, null=True)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
